Repository LikeLion-at-DGU/2025-FE-Github-Flow-Session, pull requests merged in 2025-06, with the labels that each got.

#27 feature/#7: printCountUser 구현
  yeonbee.js
Labels: 연비

#26 feature/#9: 콘솔로그작성
  printname_sw.js
Labels: 선우

#24 Feature/#5 implement print product
  jiyeon-baek.js
Labels: 지연

#23 feature/#14:js문
  won.js
Labels: won

#22 feature/#12:printName 구현
  seoyeon.js
Labels: 서연

#19 feature/#8: script.js 구현
  script.js
Labels: 수연
